# Generated by Django 3.1.5 on 2021-03-12 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentIntent',
        ),
    ]
